
// THIS FILE IS AUTO-GENERATED BY BUILD STEP
// import type * as VueJSX from '@vue/runtime-dom';
// import type { JSX as QwikJSX } from '@builder.io/qwik/jsx-runtime';
// import type { JSX as ReactJSX } from 'react';
// import type { JSX as SolidJSX } from 'solid-js';
// import type { SvelteHTMLElements } from 'svelte/elements';

export * from './u-datalist/u-datalist'

// export type VueDetails = VueJSX.DetailsHTMLAttributes;
// export type QwikDetails = QwikJSX.IntrinsicElements['details'];
// export type ReactDetails = ReactJSX.IntrinsicElements['details'];
// export type SolidJSDetails = SolidJSX.HTMLElementTags['details'];
// export type SvelteDetails = SvelteHTMLElements['details'];

// // Augmenting @vue/runtime-dom instead of vue firectly to avoid interfering with React JSX
// declare module '@vue/runtime-dom' { export interface GlobalComponents { 'u-details': VueDetails } }
// declare module '@builder.io/qwik/jsx-runtime' { export namespace JSX { export interface IntrinsicElements { 'u-details': QwikDetails } } }
// declare global { namespace React.JSX { interface IntrinsicElements { 'u-details': ReactDetails } } }
// declare module 'solid-js' { namespace JSX { interface IntrinsicElements { 'u-details': SolidJSDetails } } }
// declare module 'svelte/elements' { interface SvelteHTMLElements { 'u-details': SvelteDetails } }

export * from './u-details/u-details'


// export type VueOption = VueJSX.OptionHTMLAttributes;
// export type QwikOption = QwikJSX.IntrinsicElements['option'];
// export type ReactOption = ReactJSX.IntrinsicElements['option'];
// export type SolidJSOption = SolidJSX.HTMLElementTags['option'];
// export type SvelteOption = SvelteHTMLElements['option'];

// // Augmenting @vue/runtime-dom instead of vue firectly to avoid interfering with React JSX
// declare module '@vue/runtime-dom' { export interface GlobalComponents { 'u-option': VueOption } }
// declare module '@builder.io/qwik/jsx-runtime' { export namespace JSX { export interface IntrinsicElements { 'u-option': QwikOption } } }
// declare global { namespace React.JSX { interface IntrinsicElements { 'u-option': ReactOption } } }
// declare module 'solid-js' { namespace JSX { interface IntrinsicElements { 'u-option': SolidJSOption } } }
// declare module 'svelte/elements' { interface SvelteHTMLElements { 'u-option': SvelteOption } }

export * from './u-option/u-option'


// export type VueProgress = VueJSX.ProgressHTMLAttributes;
// export type QwikProgress = QwikJSX.IntrinsicElements['progress'];
// export type ReactProgress = ReactJSX.IntrinsicElements['progress'];
// export type SolidJSProgress = SolidJSX.HTMLElementTags['progress'];
// export type SvelteProgress = SvelteHTMLElements['progress'];

// // Augmenting @vue/runtime-dom instead of vue firectly to avoid interfering with React JSX
// declare module '@vue/runtime-dom' { export interface GlobalComponents { 'u-progress': VueProgress } }
// declare module '@builder.io/qwik/jsx-runtime' { export namespace JSX { export interface IntrinsicElements { 'u-progress': QwikProgress } } }
// declare global { namespace React.JSX { interface IntrinsicElements { 'u-progress': ReactProgress } } }
// declare module 'solid-js' { namespace JSX { interface IntrinsicElements { 'u-progress': SolidJSProgress } } }
// declare module 'svelte/elements' { interface SvelteHTMLElements { 'u-progress': SvelteProgress } }

export * from './u-progress/u-progress'

export * from './u-tabs/u-tabs'