
// THIS FILE IS AUTO-GENERATED BY BUILD STEP
import type * as VueJSX from '@vue/runtime-dom'
import type { JSX as QwikJSX } from '@builder.io/qwik/jsx-runtime'
import type { JSX as ReactJSX } from 'react'
import type { JSX as SolidJSX } from 'solid-js'
import type { SvelteHTMLElements } from 'svelte/elements'


export type VueDatalist = VueJSX.IntrinsicElementAttributes['datalist']
export type QwikDatalist = QwikJSX.IntrinsicElements['datalist']
export type ReactDatalist = ReactJSX.IntrinsicElements['datalist']
export type SolidJSDatalist = SolidJSX.HTMLElementTags['datalist']
export type SvelteDatalist = SvelteHTMLElements['datalist']

// Augmenting @vue/runtime-dom instead of vue directly to avoid interfering with React JSX
declare module '@vue/runtime-dom' { export interface GlobalComponents { 'u-datalist': VueDatalist } }
declare module '@builder.io/qwik/jsx-runtime' { export namespace JSX { export interface IntrinsicElements { 'u-datalist': QwikDatalist } } }
declare global { namespace React.JSX { interface IntrinsicElements { 'u-datalist': ReactDatalist } } }
declare module 'solid-js' { namespace JSX { interface IntrinsicElements { 'u-datalist': SolidJSDatalist } } }
declare module 'svelte/elements' { interface SvelteHTMLElements { 'u-datalist': SvelteDatalist } }
export * from './u-datalist.ts'

export type VueDetails = VueJSX.IntrinsicElementAttributes['details']
export type QwikDetails = QwikJSX.IntrinsicElements['details']
export type ReactDetails = ReactJSX.IntrinsicElements['details']
export type SolidJSDetails = SolidJSX.HTMLElementTags['details']
export type SvelteDetails = SvelteHTMLElements['details']

// Augmenting @vue/runtime-dom instead of vue directly to avoid interfering with React JSX
declare module '@vue/runtime-dom' { export interface GlobalComponents { 'u-details': VueDetails } }
declare module '@builder.io/qwik/jsx-runtime' { export namespace JSX { export interface IntrinsicElements { 'u-details': QwikDetails } } }
declare global { namespace React.JSX { interface IntrinsicElements { 'u-details': ReactDetails } } }
declare module 'solid-js' { namespace JSX { interface IntrinsicElements { 'u-details': SolidJSDetails } } }
declare module 'svelte/elements' { interface SvelteHTMLElements { 'u-details': SvelteDetails } }

export type VueSummary = VueJSX.IntrinsicElementAttributes['summary']
export type QwikSummary = QwikJSX.IntrinsicElements['summary']
export type ReactSummary = ReactJSX.IntrinsicElements['summary']
export type SolidJSSummary = SolidJSX.HTMLElementTags['summary']
export type SvelteSummary = SvelteHTMLElements['summary']

// Augmenting @vue/runtime-dom instead of vue directly to avoid interfering with React JSX
declare module '@vue/runtime-dom' { export interface GlobalComponents { 'u-summary': VueSummary } }
declare module '@builder.io/qwik/jsx-runtime' { export namespace JSX { export interface IntrinsicElements { 'u-summary': QwikSummary } } }
declare global { namespace React.JSX { interface IntrinsicElements { 'u-summary': ReactSummary } } }
declare module 'solid-js' { namespace JSX { interface IntrinsicElements { 'u-summary': SolidJSSummary } } }
declare module 'svelte/elements' { interface SvelteHTMLElements { 'u-summary': SvelteSummary } }
export * from './u-details.ts'

export type VueOption = VueJSX.IntrinsicElementAttributes['option']
export type QwikOption = QwikJSX.IntrinsicElements['option']
export type ReactOption = ReactJSX.IntrinsicElements['option']
export type SolidJSOption = SolidJSX.HTMLElementTags['option']
export type SvelteOption = SvelteHTMLElements['option']

// Augmenting @vue/runtime-dom instead of vue directly to avoid interfering with React JSX
declare module '@vue/runtime-dom' { export interface GlobalComponents { 'u-option': VueOption } }
declare module '@builder.io/qwik/jsx-runtime' { export namespace JSX { export interface IntrinsicElements { 'u-option': QwikOption } } }
declare global { namespace React.JSX { interface IntrinsicElements { 'u-option': ReactOption } } }
declare module 'solid-js' { namespace JSX { interface IntrinsicElements { 'u-option': SolidJSOption } } }
declare module 'svelte/elements' { interface SvelteHTMLElements { 'u-option': SvelteOption } }
export * from './u-option.ts'

export type VueProgress = VueJSX.IntrinsicElementAttributes['progress']
export type QwikProgress = QwikJSX.IntrinsicElements['progress']
export type ReactProgress = ReactJSX.IntrinsicElements['progress']
export type SolidJSProgress = SolidJSX.HTMLElementTags['progress']
export type SvelteProgress = SvelteHTMLElements['progress']

// Augmenting @vue/runtime-dom instead of vue directly to avoid interfering with React JSX
declare module '@vue/runtime-dom' { export interface GlobalComponents { 'u-progress': VueProgress } }
declare module '@builder.io/qwik/jsx-runtime' { export namespace JSX { export interface IntrinsicElements { 'u-progress': QwikProgress } } }
declare global { namespace React.JSX { interface IntrinsicElements { 'u-progress': ReactProgress } } }
declare module 'solid-js' { namespace JSX { interface IntrinsicElements { 'u-progress': SolidJSProgress } } }
declare module 'svelte/elements' { interface SvelteHTMLElements { 'u-progress': SvelteProgress } }
export * from './u-progress.ts'

export type VueTabs = VueJSX.IntrinsicElementAttributes['div']
export type QwikTabs = QwikJSX.IntrinsicElements['div']
export type ReactTabs = ReactJSX.IntrinsicElements['div']
export type SolidJSTabs = SolidJSX.HTMLElementTags['div']
export type SvelteTabs = SvelteHTMLElements['div']

// Augmenting @vue/runtime-dom instead of vue directly to avoid interfering with React JSX
declare module '@vue/runtime-dom' { export interface GlobalComponents { 'u-tabs': VueTabs } }
declare module '@builder.io/qwik/jsx-runtime' { export namespace JSX { export interface IntrinsicElements { 'u-tabs': QwikTabs } } }
declare global { namespace React.JSX { interface IntrinsicElements { 'u-tabs': ReactTabs } } }
declare module 'solid-js' { namespace JSX { interface IntrinsicElements { 'u-tabs': SolidJSTabs } } }
declare module 'svelte/elements' { interface SvelteHTMLElements { 'u-tabs': SvelteTabs } }

export type VueTablist = VueJSX.IntrinsicElementAttributes['div']
export type QwikTablist = QwikJSX.IntrinsicElements['div']
export type ReactTablist = ReactJSX.IntrinsicElements['div']
export type SolidJSTablist = SolidJSX.HTMLElementTags['div']
export type SvelteTablist = SvelteHTMLElements['div']

// Augmenting @vue/runtime-dom instead of vue directly to avoid interfering with React JSX
declare module '@vue/runtime-dom' { export interface GlobalComponents { 'u-tablist': VueTablist } }
declare module '@builder.io/qwik/jsx-runtime' { export namespace JSX { export interface IntrinsicElements { 'u-tablist': QwikTablist } } }
declare global { namespace React.JSX { interface IntrinsicElements { 'u-tablist': ReactTablist } } }
declare module 'solid-js' { namespace JSX { interface IntrinsicElements { 'u-tablist': SolidJSTablist } } }
declare module 'svelte/elements' { interface SvelteHTMLElements { 'u-tablist': SvelteTablist } }

export type VueTab = VueJSX.IntrinsicElementAttributes['div']
export type QwikTab = QwikJSX.IntrinsicElements['div']
export type ReactTab = ReactJSX.IntrinsicElements['div']
export type SolidJSTab = SolidJSX.HTMLElementTags['div']
export type SvelteTab = SvelteHTMLElements['div']

// Augmenting @vue/runtime-dom instead of vue directly to avoid interfering with React JSX
declare module '@vue/runtime-dom' { export interface GlobalComponents { 'u-tab': VueTab } }
declare module '@builder.io/qwik/jsx-runtime' { export namespace JSX { export interface IntrinsicElements { 'u-tab': QwikTab } } }
declare global { namespace React.JSX { interface IntrinsicElements { 'u-tab': ReactTab } } }
declare module 'solid-js' { namespace JSX { interface IntrinsicElements { 'u-tab': SolidJSTab } } }
declare module 'svelte/elements' { interface SvelteHTMLElements { 'u-tab': SvelteTab } }

export type VueTabpanel = VueJSX.IntrinsicElementAttributes['div']
export type QwikTabpanel = QwikJSX.IntrinsicElements['div']
export type ReactTabpanel = ReactJSX.IntrinsicElements['div']
export type SolidJSTabpanel = SolidJSX.HTMLElementTags['div']
export type SvelteTabpanel = SvelteHTMLElements['div']

// Augmenting @vue/runtime-dom instead of vue directly to avoid interfering with React JSX
declare module '@vue/runtime-dom' { export interface GlobalComponents { 'u-tabpanel': VueTabpanel } }
declare module '@builder.io/qwik/jsx-runtime' { export namespace JSX { export interface IntrinsicElements { 'u-tabpanel': QwikTabpanel } } }
declare global { namespace React.JSX { interface IntrinsicElements { 'u-tabpanel': ReactTabpanel } } }
declare module 'solid-js' { namespace JSX { interface IntrinsicElements { 'u-tabpanel': SolidJSTabpanel } } }
declare module 'svelte/elements' { interface SvelteHTMLElements { 'u-tabpanel': SvelteTabpanel } }
export * from './u-tabs.ts'
